### ISSUE TITLE
Error in run  "pio run " or flash.py

### ISSUE THREAD

**Issue by radsonpatrick** [cvanelteren/splitboard#3] opened 2023-05-18 04:17 UTC
Thank you for your project and the accompanying documentation. I would like to express my appreciation for your efforts. I am currently testing your firmware for use in my new split keyboard, and I wanted to reach out and thank you for your work. However, I am encountering an error during the compilation process.

To reproduce the issue, I have followed these steps:

Cloned your repository using the command: 'git clone [repository URL]'
Executed the 'start.py' script or attempted to build the project using PlatformIO with 'pio run' command.
Unfortunately, during the compilation, I encountered an error. I would greatly appreciate any assistance or guidance you could provide to help me resolve this issue.

![image](https://github.com/cvanelteren/splitboard/assets/43654273/0a6cca14-6c56-4056-b71d-a0ab146de921)

Thank you once again for your project and the opportunity to use your firmware. I look forward to your response and support

**Comment by cvanelteren** [comment] 2023-05-18 06:00
Hi @radsonpatrick,

Thank you for reporting the issue and for future reference by any means ping me in any future issues. The error is caused by your machine not finding the `FreeRTOS.h` header file, and not directly caused by this software. 

[This](https://github.com/espressif/arduino-esp32/issues/5738#issuecomment-1007075234) thread may help you. Let me know if this helps!

**Comment by radsonpatrick** [comment] 2023-05-18 11:33
Hello,

I'm facing an issue while trying to use FreeRTOS in my project. I added FreeRTOS to the lib_deps (library dependencies) in my platformio.ini file, but I'm still encountering another error. I'm not entirely sure about the steps mentioned in the previous suggestions, but I followed the instructions and added FreeRTOS to the lib_deps section. However, I'm still experiencing an error.

I would appreciate any help in resolving this issue. Please find below the error message I'm currently receiving:
``` 
lib_deps =
	olikraus/U8g2
	FastLED
	FreeRTOS
	; nkolban/ESP32 BLE Arduino @ ^1.0.4
	; nkolban/ESP32 BLE Arduino
	t-vk/ESP32 BLE Keyboard
	NimBLE-Arduino
```
![image](https://github.com/cvanelteren/splitboard/assets/43654273/0a6e7faa-9c24-42b4-91ed-6b4b95ead2f1)

sorry for my english, it's not my mother tongue

**Comment by cvanelteren** [comment] 2023-05-18 12:50
> sorry for my english, it's not my mother tongue

No worries, we are all here to learn ;-). The error seems to originate from arduino. Did you install arduino in your system? If I recall correctly `arduino-avr-core` is what you need. On arch the install would be 

``` yay arduino-avr-core```
Also see the pio documentation [here](https://docs.platformio.org/en/latest/frameworks/arduino.html).

**Comment by radsonpatrick** [comment] 2023-05-18 15:11
I apologize for that. However, I installed "arduino-core-avr" in my code-server container using the command "apt-install arduino-core-avr," but the same error persists.

**Comment by cvanelteren** [comment] 2023-05-18 15:34
What does 

``` find / -name io.h``` return?

**Comment by radsonpatrick** [comment] 2023-05-18 16:18
```root@705bd27a6199:/# find / -name io.h
/usr/lib/avr/include/avr/io.h
/usr/include/x86_64-linux-gnu/sys/io.h
find: ‘/proc/242/task/242/fdinfo’: Permission denied
find: ‘/proc/242/task/255/fdinfo’: Permission denied
find: ‘/proc/242/task/256/fdinfo’: Permission denied
find: ‘/proc/242/task/257/fdinfo’: Permission denied
find: ‘/proc/242/task/258/fdinfo’: Permission denied
find: ‘/proc/242/task/259/fdinfo’: Permission denied
find: ‘/proc/242/task/260/fdinfo’: Permission denied
find: ‘/proc/242/task/265/fdinfo’: Permission denied
find: ‘/proc/242/task/266/fdinfo’: Permission denied
find: ‘/proc/242/task/267/fdinfo’: Permission denied
find: ‘/proc/242/task/268/fdinfo’: Permission denied
find: ‘/proc/242/map_files’: Permission denied
find: ‘/proc/242/fdinfo’: Permission denied
find: ‘/proc/269/task/269/fdinfo’: Permission denied
find: ‘/proc/269/task/270/fdinfo’: Permission denied
find: ‘/proc/269/task/271/fdinfo’: Permission denied
find: ‘/proc/269/task/272/fdinfo’: Permission denied
find: ‘/proc/269/task/273/fdinfo’: Permission denied
find: ‘/proc/269/task/274/fdinfo’: Permission denied
find: ‘/proc/269/task/275/fdinfo’: Permission denied
find: ‘/proc/269/task/277/fdinfo’: Permission denied
find: ‘/proc/269/task/278/fdinfo’: Permission denied
find: ‘/proc/269/task/279/fdinfo’: Permission denied
find: ‘/proc/269/task/280/fdinfo’: Permission denied
find: ‘/proc/269/map_files’: Permission denied
find: ‘/proc/269/fdinfo’: Permission denied
find: ‘/proc/281/task/281/fdinfo’: Permission denied
find: ‘/proc/281/task/282/fdinfo’: Permission denied
find: ‘/proc/281/task/283/fdinfo’: Permission denied
find: ‘/proc/281/task/284/fdinfo’: Permission denied
find: ‘/proc/281/task/285/fdinfo’: Permission denied
find: ‘/proc/281/task/286/fdinfo’: Permission denied
find: ‘/proc/281/task/296/fdinfo’: Permission denied
find: ‘/proc/281/task/342/fdinfo’: Permission denied
find: ‘/proc/281/task/343/fdinfo’: Permission denied
find: ‘/proc/281/task/344/fdinfo’: Permission denied
find: ‘/proc/281/task/345/fdinfo’: Permission denied
find: ‘/proc/281/task/731/fdinfo’: Permission denied
find: ‘/proc/281/task/8259/fdinfo’: Permission denied
find: ‘/proc/281/map_files’: Permission denied
find: ‘/proc/281/fdinfo’: Permission denied
find: ‘/proc/623/task/623/fdinfo’: Permission denied
find: ‘/proc/623/task/624/fdinfo’: Permission denied
find: ‘/proc/623/task/625/fdinfo’: Permission denied
find: ‘/proc/623/task/626/fdinfo’: Permission denied
find: ‘/proc/623/task/627/fdinfo’: Permission denied
find: ‘/proc/623/task/628/fdinfo’: Permission denied
find: ‘/proc/623/task/629/fdinfo’: Permission denied
find: ‘/proc/623/task/630/fdinfo’: Permission denied
find: ‘/proc/623/task/631/fdinfo’: Permission denied
find: ‘/proc/623/task/632/fdinfo’: Permission denied
find: ‘/proc/623/task/633/fdinfo’: Permission denied
find: ‘/proc/623/task/634/fdinfo’: Permission denied
find: ‘/proc/623/task/635/fdinfo’: Permission denied
find: ‘/proc/623/map_files’: Permission denied
find: ‘/proc/623/fdinfo’: Permission denied
find: ‘/proc/730/task/730/fdinfo’: Permission denied
find: ‘/proc/730/map_files’: Permission denied
find: ‘/proc/730/fdinfo’: Permission denied
find: ‘/proc/7640/task/7640/fdinfo’: Permission denied
find: ‘/proc/7640/task/7645/fdinfo’: Permission denied
find: ‘/proc/7640/task/7646/fdinfo’: Permission denied
find: ‘/proc/7640/task/7647/fdinfo’: Permission denied
find: ‘/proc/7640/task/7648/fdinfo’: Permission denied
find: ‘/proc/7640/task/7649/fdinfo’: Permission denied
find: ‘/proc/7640/task/7659/fdinfo’: Permission denied
find: ‘/proc/7640/task/7682/fdinfo’: Permission denied
find: ‘/proc/7640/task/7683/fdinfo’: Permission denied
find: ‘/proc/7640/task/7684/fdinfo’: Permission denied
find: ‘/proc/7640/task/7685/fdinfo’: Permission denied
find: ‘/proc/7640/task/7866/fdinfo’: Permission denied
find: ‘/proc/7640/map_files’: Permission denied
find: ‘/proc/7640/fdinfo’: Permission denied
find: ‘/proc/7658/task/7658/fdinfo’: Permission denied
find: ‘/proc/7658/task/7660/fdinfo’: Permission denied
find: ‘/proc/7658/task/7661/fdinfo’: Permission denied
find: ‘/proc/7658/task/7662/fdinfo’: Permission denied
find: ‘/proc/7658/task/7663/fdinfo’: Permission denied
find: ‘/proc/7658/task/7664/fdinfo’: Permission denied
find: ‘/proc/7658/task/7673/fdinfo’: Permission denied
find: ‘/proc/7658/task/7698/fdinfo’: Permission denied
find: ‘/proc/7658/task/7699/fdinfo’: Permission denied
find: ‘/proc/7658/task/7700/fdinfo’: Permission denied
find: ‘/proc/7658/task/7701/fdinfo’: Permission denied
find: ‘/proc/7658/task/7706/fdinfo’: Permission denied
find: ‘/proc/7658/task/7707/fdinfo’: Permission denied
find: ‘/proc/7658/map_files’: Permission denied
find: ‘/proc/7658/fdinfo’: Permission denied
find: ‘/proc/8250/task/8250/fdinfo’: Permission denied
find: ‘/proc/8250/map_files’: Permission denied
find: ‘/proc/8250/fdinfo’: Permission denied
/config/.platformio/packages/toolchain-atmelavr/avr/include/avr/io.h
root@705bd27a6199:/# ```

**Comment by cvanelteren** [comment] 2023-05-18 16:52
> /usr/lib/avr/include/avr/io.h

That one is the one you need.  It seems like it is correctly installed. Therefore, this implies that you may have a pathing issue. However, the last line also has has one listed under config which is a bit worrying. I am not sure if you changed anything with the local configs. If so please revert the changed repo and or files to the original locations. I am closing this issue for now as it is not a issue with this repo. Please refer to the corresponding docs of platformio io for the correct installation.

**Closed as completed by cvanelteren** 2023-05-18 16:52 UTC
Labels: documentation

**Comment by cvanelteren** [comment] 2023-05-18 16:54
Try and see if you can get [this](https://docs.platformio.org/en/latest/tutorials/espressif32/arduino_debugging_unit_testing.html#tutorial-espressif32-arduino-debugging-unit-testing) running in a separate folder.

**Comment by radsonpatrick** [comment] 2023-05-18 17:00
ok thank you im go new container for test... not necesarry add lib deps in platformio.ini ? 

```lib_deps =
	olikraus/U8g2
	FastLED
	FreeRTOS  //  not need this ?
	; nkolban/ESP32 BLE Arduino @ ^1.0.4
	; nkolban/ESP32 BLE Arduino
	t-vk/ESP32 BLE Keyboard
	NimBLE-Arduino```

**Comment by cvanelteren** [comment] 2023-05-18 17:02
I don't think so. The avr module is part of Arduino I think. The installation should be handled by platformio instructions.

**Comment by radsonpatrick** [comment] 2023-05-18 17:03
ok,  thank you  ! i'm go resolve problem in my enviroment

**Comment by cvanelteren** [comment] 2023-05-18 17:11
Hope it gets resolved. Please report back, perhaps I can add something in the docs that may help a future explorer.
